# Please insert new items alphabetically.

core-formats:
  members:
    - extracreative
    - phpengine
    - plimbs

  repos:
    - nu-wordpress-platform

  channel:
    "#wp-platform-seal"

  exclude_titles:
    - "[DO NOT MERGE]"
    - DO NOT MERGE
    - WIP


